### PR TITLE
Snow melt computation bug.

### PR DESCRIPTION
**Pull request by dabail10**
For detailed information about submitting Pull Requests (PRs) to the CICE-Consortium,
please refer to: <https://github.com/CICE-Consortium/About-Us/wiki/Resource-Index#information-for-developers>

## PR checklist
- [X] Short (1 sentence) summary of your PR: 
When the sea ice completely melts away in the thermodynamics, the final little bit of snow melt is not added to the melts array.
- [X] Developer(s): 
dabail10 (D. Bailey)
- [X] Suggest PR reviewers from list in the column to the right.
- [X] Please copy the PR test results link or provide a summary of testing completed below.
https://github.com/CICE-Consortium/Test-Results/wiki/icepack_by_mach_forks#izumi
- How much do the PR code changes differ from the unmodified code? 
    - [ ] bit for bit
    - [X] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on CICE or any other models?
    - [ ] Yes
    - [X] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [X] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/.)
    - [ ] Yes
    - [X] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [X] No 
- [X] Please provide any additional information or relevant details below:
This changes answers in 18 of the base_suite tests in Icepack. I have run the QC suite within CICE and it passes. It's interesting that the biggest differences are in the Weddell Sea, but they are still on the order of 1cm. Here are the plots:

ice_thickness_izumi_nag_smoke_gx1_48x1_medium_qc qc_base

ice_thickness_izumi_nag_smoke_gx1_48x1_medium_qc qc_te

ice_thickness_izumi_nag_smoke_gx1_48x1_medium_qc qc_base_minus_izumi_nag_smoke_gx1_48x1_medium_qc qc_te

### CODE REVIEW

**Comment by dabail10** [comment]
Jiang Zhu is a new project scientist at NCAR. He found this while working on his PhD and bringing in water isotopes into CICE.

**Comment by apcraig** [comment]
I just want to clarify the non bit-for-bit results.  It looks like a40bbf9 was bit-for-bit except for 18 tests with the pgi compiler (intel, nag, and gnu were bit-for-bit).  But then the regression tests with faa181f were all bit-for-bit against the exact same baseline version except for 1 test.  I don't understand these results.  Why are the test results not consistent and why are the pgi results not bit-for-bit when the other compilers are?

Also, I guess I would expect all answers to change.  Was a test suite run with CICE to see whether the results change for all configurations?

I think we can merge this, we know it's a bug fix.  I guess I'm just trying to better understand the test results we're seeing and to make sure it's consistent with what we expect.

**Comment by dabail10** [comment]
I only ran the QC test for one configuration. I will run the CICE base_suite as well.

**Comment by dabail10** [comment]
The CICE base_suite will have to wait until Monday when cheyenne is back up.

**Comment by dabail10** [comment]
I had that wrong. I already did the QC test. I am running the base_suite on cheyenne against the baselines.

**Comment by dabail10** [comment]
Here are the CICE base_suite results:

https://github.com/CICE-Consortium/Test-Results/wiki/cice_by_mach_forks#cheyenne

Not sure why gnu only has two answer changing cases. It looks like it just takes longer for the answer changes to come up and hence show up in the 90 day and 1 year tests?

**Comment by apcraig** [comment]
Thanks for doing the extra testing.  Good to know what kinds of changes we should expect when we pull it into CICE.

**Pull request merged**
