### PR TITLE
Add argcheck and clean up code

### PR DESCRIPTION
**Pull request by apcraig**
## PR checklist
- [X] Short (1 sentence) summary of your PR: 
    Add argcheck parameter and clean up code
- [X] Developer(s): 
    apcraig
- [X] Suggest PR reviewers from list in the column to the right.
- [X] Please copy the PR test results link or provide a summary of testing completed below.
    All tests pass on cheyenne with Icepack and CICE, https://github.com/CICE-Consortium/Test-Results/wiki/icepack_by_hash_forks#878af2655de602fa415125b0bfc8e29ad675f27e, https://github.com/CICE-Consortium/Test-Results/wiki/cice_by_hash_forks#e630284d5baa877f93c8ca3003bcb2fa8c27e63f
- How much do the PR code changes differ from the unmodified code? 
    - [X] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on CICE or any other models?
    - [ ] Yes
    - [X] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [X] No, modifies some of the names of the options
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/.)
    - [X] Yes
    - [ ] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [ ] No 
- [X] Please provide any additional information or relevant details below:

- Add argcheck parameter, not used yet
- Rename options so all lowercase, needed for consistent alphabetical sort
- Clean up unused variables found by compile with -Wall
- Remove trailing blanks

### CODE REVIEW

**Comment by phil-blain** [comment]
This looks good, two comments:
- do we want to add `-Wall` to some machines files in order to not introduce more unused variables ? How "clean" are we at the moment ? (also, which compiler was used to find these?)
- I'm not sure I understand how this `argcheck` setting will be used. It would be nice to see an explanation:)

**Review by dabail10 — APPROVED** [review]
This is a lot of work! Looks reasonable to me. I guess there were some variables related to the deprecated options that we forgot about.

**Comment by apcraig** [comment]
I used -Wall on gnu and cleaned up what was easy.  There are some variables that are passed as arguments in subroutines that are not used, but I chose not to clean those up.  There were other warning messages that also weren't reasonable to cleanup, like a return statement after an abort and before and output variable was set.  -Wall did not reveal too many things.  I thought about adding it to one of the machines, but decided not to.  I think this is something we can run occasionally, but I don't think it's something we need to have on by default.  @phil-blain, if you want to add it to one of your machines, that's fine :).

**Comment by apcraig** [comment]
The argcheck parameter planning documentation is here,

https://github.com/CICE-Consortium/Icepack/files/9004010/Icepack_Package-2.pptx  on slide 14.

The idea is that optional arguments checking could be turned off, done at "first call", or done at every call.  We may add other options later.  I agree some of this needs to be added to the user guide.  I think we can do that as we make progress adding new optional arguments and seeing how that works out.

**Pull request merged**
