### PR TITLE
Icepack Index

### PR DESCRIPTION
**Pull request by duvivier**
Update to the Icepack index of variables to address Issue #80.

Developer(s): Alice DuVivier
Are the code changes bit for bit, different at roundoff level, or more substantial? Bit for Bit
Is the documentation being updated with this PR? (Y/N) Y
If not, does the documentation need to be updated separately? (Y/N) N/A
"Documentation" includes information on the wiki and .rst files in doc/source/, 
which are used to create the online technical docs at https://cice-consortium.github.io/Icepack/ 
Please suggest code reviewers in the column at right. 
Other Relevant Details:

All, I've gone through the Icepack index and removed variables that are no longer relevant. I just grepped through the code, so it's possible I made mistakes removing some of these or need to remove more. Please go through and double check these!

### CODE REVIEW

**Comment by eclare108213** [comment]
Thanks @dabail10 
Some of the things you've listed should be removed, and indeed I removed some of them from the code this weekend (still in my fork).  But some of them are still in there even though we might not need them for the column physics, because they are sent through subroutine calls for other purposes. I.e. even though they might not make sense in Icepack itself, they do make sense in the context of a full sea ice model, so we've kept them.  I recommend that for each of the items noted above, we look at the code to see how it's used and whether it makes sense to remove or keep, and then do the same thing for both the code and the documentation.   I recommend to work from the code base after my fork is merged (or look at my fork, for now).

**Comment by duvivier** [comment]
Elizabeth, have you updated the code from your fork where you removed some of these yet? I just wanted to check before I start a new documentation branch/pr. I didn't see icepack_index.rst changed in any of the recent PR's.

**Comment by eclare108213** [comment]
@duvivier My fork has been merged into the main repo now.

**Comment by duvivier** [comment]
Dave, Elizabeth. I went through Dave's comments after Elizabeth's additions. I've noted the changes I've made or the place in the code the variable lives. Do you think we should remove any of the things still in the code but that Dave highlighted?

alvdr, alvdf, alidr, and alidf --> not sure what the issue was, I'll break these out to make it clearer
daidtd, dvidtd, daidtt, and dvidtt : icedrv_flux.F90
iceumask --> removed
kstrength : icepack_parameters.F90:214
nprocs --> removed
prs_sig --> removed
Pstar : icepack_parameters.F90:223
radius : icedrv_constants.F90:70
sig1 and sig2 --> removed
swvdr, swvdf, swidr, and swidf --> not sure what the issue was. I'll break these out to make it clearer.
umask --> removed
write_ic : icedrv_calendar.F90:90

**Comment by eclare108213** [comment]
Let's keep daidtd etc - might be useful even if we aren't using them now.
We might want to look at kstrength when we put in the new ridging scheme.  Pstar probably goes with it.
If radius isn't used, let's take it out of the code and the doc.
Let's remove write_ic also; it's easy enough to add another write statement manually, if needed.
The rest looks good, thanks.

**Pull request merged**
