### PR TITLE
Cleaning documentation

### PR DESCRIPTION
**Pull request by duvivier**
Cleaning up the documentation to respond to Elizabeth's issue #63, Issue #67 , and Issue #74 . Please also check the pdf generated from the new RST under /doc/Icepack.pdf as well as the HTML. Updated year to 2018 and Icepack release to V1.0.

Removed the "sphinx" guides since that info is now in the wiki", and changed Readme.ME overall so that it points to the correct paths.

Developer(s): Alice DuVivier
Are the code changes bit for bit, different at roundoff level, or more substantial? bit for bit
Is the documentation being updated with this PR? (Y/N) Y
If not, does the documentation need to be updated separately? (Y/N) N
"Documentation" includes information on the wiki and .rst files in doc/source/, 
which are used to create the online technical docs at https://cice-consortium.github.io/Icepack/ 
Please suggest code reviewers in the column at right. 
Other Relevant Details:

### CODE REVIEW

**Comment by duvivier** [comment]
Elizabeth,
I don't know. It does 194 files are changed but then when I open them it says "No Change" for most of them, including code. The ones that do show changes are the documentation files I did change. I'm not savvy enough with Git yet to know how to resolve this on my own. Thoughts? I did a git pull on the latest changes from the consortium branch immediately before I did my own commit and the PR. That's the only time I think these files would have been part of the git process.

**Comment by eclare108213** [comment]
I think @apcraig might need to help on this one.  My inclination would be to start over with a fresh branch, update your fork if it needs it, then copy the changed files into the branch and add/delete as needed, commit and PR again.  But if the problem is in your fork, I'll not be much help.  There is a conflict, but probably that file was changed before being deleted when your refactored all the files.

**Comment by duvivier** [comment]
My inclination is also to start over, but it seems silly to have to do this repeatedly. Maybe this is the "rebasing" thing you can do in github but I don't quite understand that fully, to be honest. I can start fresh though, that should make things cleaner for sure. I'll try to get it all done later tonight.

**Comment by apcraig** [comment]
It looks like it's permissions changes on files that is being committed.  Might want to fix that.

**Comment by duvivier** [comment]
I will go ahead and re-start my fork and branch to include these changes without the permissions issue. I'm going to close this PR and start again.

**Pull request closed without merging**
