### PR TITLE
Add saltflux option.

### PR DESCRIPTION
**Pull request by dabail10**
For detailed information about submitting Pull Requests (PRs) to the CICE-Consortium,
please refer to: <https://github.com/CICE-Consortium/About-Us/wiki/Resource-Index#information-for-developers>

## PR checklist
- [X] Short (1 sentence) summary of your PR: 
This adds the option to do a "constant" salinity reference for the salt and fresh water fluxes versus a 'prognostic' option that uses the mushy-layer prognostic salinity. 
- [X] Developer(s): 
dabail10 (D. Bailey)
- [X] Suggest PR reviewers from list in the column to the right.
- [X] Please copy the PR test results link or provide a summary of testing completed below.
Bfb with aux_cice suite in CESM.
https://github.com/CICE-Consortium/Test-Results/wiki/icepack_by_hash_forks#b3b48bf7a7b27c6cf4d89261151bbee0f15a525d
- How much do the PR code changes differ from the unmodified code? 
    - [x] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on CICE or any other models?
    - [X] Yes
    - [ ] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [X] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/.)
    - [X] Yes
    - [ ] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [ ] No 
- [X] Please provide any additional information or relevant details below:
There is an associated CICE tag to go with this.

### CODE REVIEW

**Comment by apcraig** [comment]
Please do standalone Icepack testing including regression testing.

**Comment by dabail10** [comment]
I did the Icepack regression testing with intel, pgi, and gnu on cheyenne. Everything is bfb.

**Review by apcraig — APPROVED** [review]
Looks good.  Do we need to add a test for saltflux_option = prognostic in Icepack and/or CICE?

**Comment by dabail10** [comment]
I agree. I should probably add tests for both.

**Comment by apcraig** [comment]
Sounds good.  Maybe we can merge the Icepack PR today and the CICE PR in the next day or two then I can start testing for the release.  Thanks!

**Comment by apcraig** [comment]
How about if we call the salt test "saltprog" instead of just "salt"?  Does the new test pass?

**Comment by dabail10** [comment]
If we are doing a longer name I would prefer saltflux.

**Comment by dabail10** [comment]
The test passes in CICE with the updated Icepack submodule.

**Comment by apcraig** [comment]
saltflux is OK too.  Or saltfluxprog.  Can you also do a quick run with standalone Icepack for the new test.  Lets just make sure it runs and passes.  Then we can merge.  Thanks!

**Comment by dabail10** [comment]
Did quick_suite on intel.

./icepack.setup --suite quick_suite --mach cheyenne --env intel --testid saltflux4 -s saltflux

10 measured results of 10 total results
10 of 10 tests PASSED
0 of 10 tests PENDING
0 of 10 tests MISSING data
0 of 10 tests FAILED

**Comment by apcraig** [comment]
The new test is in the base_suite.

**Comment by apcraig** [comment]
OK, I see you ran quick_suite with -s saltflux.  I guess that's OK too.

**Comment by dabail10** [comment]
Whoops. Should be there now.

**Pull request merged**
