### PR TITLE
Fix restart

### PR DESCRIPTION
**Pull request by chrisknewman**
NICE and NICE with bgc ready for testing
Developer(s): Chris Newman
Updated documentation (Y/N): N
Results (bit for bit, roundoff, climate changing): bit for bit
Code review: @eclare108213 looked at it some last week
Other Relevant Details:

### CODE REVIEW

**Comment by eclare108213** [comment]
@chrisknewman are the data needed to runs these tests already in the tar file on ftp?

**Comment by chrisknewman** [comment]
@eclare108213 The data files were contained in the tarball I provided to Dave.  I have input files locally.

**Comment by eclare108213** [comment]
@chrisknewman Please add the appropriate settings files for the NICE case in configuration/scripts/options.
@njeffery Would you check the settings for both NICE and ISPOL to make sure we are testing these correctly?  
Thanks!

**Comment by chrisknewman** [comment]
@eclare108213 I think this might be ready now...

**Comment by njeffery** [comment]
Chris and Elizabeth,


Looks almost there. I think the istep0 and npt are not correct for a 1 hour timestep.  I have a test in the queue now.  There also appears to be a typo in the NICE forcing name in icedrv_forcing.F90.  "NICE_atm_forcing.txt" is mispelled  "NICEL_atm_forcing.txt"


Nicole

________________________________

**Comment by eclare108213** [comment]
What timestep do you use?  30 min?
e

**Comment by eclare108213** [comment]
The forcing file name was corrected in this version.  @njeffery please make other corrections e.g. namelist options in a new PR.  I am merging this one now so that I can clean up the code.

**Pull request merged**
