### PR TITLE
Automated testing with Travis continuous integration

### PR DESCRIPTION
**Pull request by anders-dc**
# What and why?
This pull request adds continuous integration to [github.com/CICE-Consortium/Icepack](https://github.com/CICE-Consortium/Icepack) using [Travis-CI](https://travis-ci.org), which runs the entire `base_suite` of tests for *every commit and pull request* submitted to this repository. The continued testing makes it easy to identify if a commit or pull request breaks or fixes any of the tested functionality. Every run takes place in a clean Ubuntu 14 LTS environment using `gfortran` and `clang`, as Intel compilers are not available here.

This pull request is fully up-to-date with the master branch of CICE-Consortium/Icepack, including yesterday's merge #113. 

## Example build log
An example Travis-CI build log can be seen [here](https://travis-ci.org/anders-dc/Icepack/builds/336607165). As the testing is quite verbose, the output is truncated on the webpage. While the build correctly identifies the overall status of the test suite (passed or failed), the [raw log](https://api.travis-ci.org/v3/job/336607166/log.txt) contains the entire output. In this particular build, 2 of the 54 tests failed (`travisCI_gnu_smoke_col_1x1_bgcISPOL_debug run` and `travisCI_gnu_restart_col_1x1_bgcISPOL run-initial`), which results in the "Failed" status for the build. These are the failed tests referenced in issue #96.

# Actions required from CICE-Consortium
Travis-CI needs access to the Github repository to continuously monitor commits and pull requests. A person with administrative credentials to the [github.com/CICE-Consortium](https://github.com/CICE-Consortium) needs to sign in to [travis-ci.org](https://travis-ci.org), and accept the Github access permissions confirmation. Afterwards, the Icepack repository needs to be enabled on the Travis-CI profile page. 

For further details on the procedure, see the [official documentation](https://docs.travis-ci.com/user/getting-started#To-get-started-with-Travis-CI).

# Questionnaire
*Developer(s):* Anders Damsgaard, Princeton/NOAA-GFDL ([github.com/anders-dc](https://github.com/anders-dc), [adamsgaard.dk](https://adamsgaard.dk))

*Are the code changes bit for bit, different at roundoff level, or more substantial?* There are no changes to the underlying code. This pull request adds a `.travis.yml` file in the repository root along with scripts in (`configuration/scripts/machines`) to setup the build environment. Furthermore, the test script is modified to return the status to the output shell, which should be inconsequential for other uses.

*Is the documentation being updated with this PR? (Y/N)* No.

*If not, does the documentation need to be updated separately? (Y/N)* No. Maybe I will put in a minor pull request to the developer's guide later.

### CODE REVIEW

**Comment by apcraig** [comment]
This is awesome.  Thank you.

**Comment by anders-dc** [comment]
It is certainly possible to run `report_results.csh` from travis-CI, but would the instance be able to push to the wiki repo? Also, I guess the command should be appended as `; report_results.csh` so that failures are reported as well.

**Comment by anders-dc** [comment]
The only mandatory change to `icepack.create.case` is the line `exit \$failures`, the other changes were for debugging. Sorry for not reverting these.

**Comment by apcraig** [comment]
We would have to find a way to give permission for travisci to push to the wiki.  We have considered providing a generic git username/password that anyone could use to write to the wiki.  That would probably work.  We could also give travisci it's own.  Even if it were visible, that would probably be OK.  We would like the test results wiki to be open-ish anyway, we've been thinking about how to do that and how open it should be.

**Comment by apcraig** [comment]
@anders-dc , we are interested in moving this forward.  we have just introduced some changes to the scripts, so we'll need to revise this PR.  I am happy to do that or if you can, that's great too.  The changes would be to that
  icepack.create.case is now named icepack.setup and the arguments were updated
  we have made some small changes to the env (and maybe but probably not Macros) file, there is a new MACHCOMP env variable there

If those could be updated and tested first, that would be great.  Then I will take steps to get travis working with the cice-consortium icepack repo (thank you for all the detailed instructions).  Finally, we'll want results reported back to the wiki as well, so we can figure out how to do that best.  @anders-dc, thank you again for your efforts on this, it is great!  I may need some help from you to get this all working from the consortium side.  I hope that's OK.

Again, @anders-dc  if you want me to take on the first step, revising the PR to be up to date with the latest changes (it should be minor), I am happy to do that.  Just let me know.

**Comment by anders-dc** [comment]
Hi @apcraig,

Sounds great, I'll go ahead and rename the `icepack.create.case` script to `icepack.setup`, and implement the described changes to the files `configuration/scripts/{Macros,env}.travisCI_gnu`.

Could you detail what is required for pushing to the wiki from `report_results.csh`? We can make a dedicated Github user for that if necessary, and I can help implement that on the Travis side through your account. You can send any details you don't want in public discussion to [andersd@princeton.edu](mailto:andersd@princeton.edu). Maybe it is worth getting Travis-CI up and running first, and do a separate pull request implementing the wiki results reporting afterwards? Your call.

Cheers, Anders

**Comment by anders-dc** [comment]
The commit b224429 contains the changes regarding `icepack.setup`. I do not see the environment variable called MACHCOMP in any of the files in `configuration/scripts/machines`?

**Comment by apcraig** [comment]
Sorry about that.  You are right that the new env variables are not in the env file.  The changes looks good.  I agree we can wait on the test reporting to a later step.

I have logged into travis-ci and enabled the icepack repo on the travis side.  Will take this offline for further discussion.

**Pull request merged**
