### PR TITLE
Refactor6

### PR DESCRIPTION
**Pull request by apcraig**
Clean up "use" of icepack_constants using instead query function as much as reasonable.

Developer(s): tcraig
Are the code changes bit for bit, different at roundoff level, or more substantial? bit-for-bit
Is the documentation being updated with this PR? (Y/N) N
If not, does the documentation need to be updated separately? (Y/N) N
"Documentation" includes information on the wiki and .rst files in doc/source/, 
which are used to create the online technical docs at https://cice-consortium.github.io/Icepack/ 
Please suggest code reviewers in the column at right. 
Other Relevant Details:

### CODE REVIEW

**Comment by apcraig** [comment]
I decided to use constants that were parameters and query the others.  In fact, we can go to all-query and maybe should for completeness.  I agree that secday should probably not be a parameter and should then not be used.  I can fix this.  Do you want me to migrate all constants (including true parameters like c0) to query only?

**Comment by eclare108213** [comment]
No, I'd rather we just "use" things that are true numbers and shouldn't be available for users to change.  Anything with units should be queried, and unitless numbers that are nevertheless somewhat arbitrary, like puny.  Does that rule cover everything?

**Comment by eclare108213** [comment]
On the other hand...
If we don't use any constants, then our external code developers would be less likely to avoid coding the query calls by using their newly implemented parameters/constants.  It might be less confusing and easier to deal with, overall.

**Comment by apcraig** [comment]
Can you clarify what you are suggesting with the "other hand".  What does "if we don't use any constants" mean?

**Comment by eclare108213** [comment]
Sorry, I mean "use" as in Fortran "use".  If the only apparent option in the code is to query for things, then developers would be less likely to implement their code with use statements instead of queries, for tuning parameters and such.

**Comment by apcraig** [comment]
I agree.  The other option is that we can easily duplicate the hardcoded parameters, c0, c1, p1, etc in the icedrv_constants directly.  Yes, we would have two copies of the same parameters, but these are well defined so it should be OK.  In fact, maybe that is the right way to do it.  Sharing those constants across the icepack interfaces doesn't really make a lot of sense.

**Comment by eclare108213** [comment]
Yes, and host models other than cice will probably have different names for things like that, e.g. zero, half, one, etc, so it makes even more sense from their point of view to define those in both places.

**Comment by apcraig** [comment]
I just commited a change to the constant parameters and secday.  There is a copy of the constant parameters in the driver now.  I also made secday a non-parameter in the columnphysics and added secday to icedrv_calendar as a public scalar for the driver.  A query during initialization sets the secday in the driver.

**Comment by eclare108213** [comment]
This works for me.  Let's make sure to include the philosophy behind the constants/parameters/tracer init/query routines in the documentation, i.e. that the host model "owns" the data and communicates it to/from Icepack.

**Pull request merged**
