### PR TITLE
Add warning for FSD without waves, clarify documentation 

### PR DESCRIPTION
**Pull request by lettie-roach**
For detailed information about submitting Pull Requests (PRs) to the CICE-Consortium,
please refer to: <https://github.com/CICE-Consortium/About-Us/wiki/Resource-Index#information-for-developers>

## PR checklist
- [x] Short (1 sentence) summary of your PR: 
    Add warning for FSD without waves, clarify documentation 
- [x] Developer(s): 
   Lettie Roach
- [x] Suggest PR reviewers from list in the column to the right.
 @eclare108213 @apcraig 
- [ ] Please copy the PR test results link or provide a summary of testing completed below.
    None
- How much do the PR code changes differ from the unmodified code? 
    - [x] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on CICE or any other models?
    - [ ] Yes
    - [x] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [x] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/.)
    - [x] Yes
    - [ ] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [ ] No 
- [ ] Please provide any additional information or relevant details below:

(@eclare108213 edited to to remove spaces from the checkboxes)

### CODE REVIEW

**Review by eclare108213 — COMMENTED** [review]
This can be merged as soon as we make the new wave forcing file available, along with the CICE changes in https://github.com/CICE-Consortium/CICE/pull/775.

**Review by apcraig — APPROVED** [review]

**Comment by apcraig** [comment]
This all looks pretty straight-forward, not sure where a new file comes in.  I think this can be merged as is unless there are other things to do.

**Comment by lettie-roach** [comment]
Is there already a wave spectrum file for a whole year available? If so, then no extra file is needed. Cheyenne is down at the moment so I can't check what's in the ocn_data_dir

**Comment by apcraig** [comment]
The file we're using now for testing is ww3.20100101_efreq_remapgx3.nc.  That file seems to have 6 hourly data for 1 day.

```
	time = UNLIMITED ; // (4 currently)
		time:units = "days since 1990-01-01 00:00:00" ;
 time = 7305, 7305.25, 7305.5, 7305.75 ;
```

**Pull request merged**
