### PR TITLE
Add back in restore_ocn and trestore flags to icepack_in.

### PR DESCRIPTION
**Pull request by dabail10**
Add back in restore_ocn and trestore flags to icepack_in.
Developer(s): D. Bailey
Updated documentation (Y/N): N
Results (bit for bit, roundoff, climate changing): bfb
Code review: E. Hunke
Other Relevant Details:

### CODE REVIEW

**Comment by apcraig** [comment]
This seems to include PR #32, should we delete PR #32?  Would it be easier to just work on a single branch for this set of changes and continue to push updates on that working branch?

**Comment by dabail10** [comment]
I assumed that we would still do it in stages. So accept PR #32 and then do #33. I will use the same branch in the future.

**Comment by apcraig** [comment]
either way is ok, just checking.

**Comment by apcraig** [comment]
OK, after merging #32, this now has a conflict.  Not sure why.  Dave, can you check.

**Comment by dabail10** [comment]
Ok. There was a commit made where my branch was not up to date with master. I have resynced with master and am issuing a new PR.

**Pull request closed without merging**
