### PR TITLE
Updated html from merge 52

### PR DESCRIPTION
**Pull request by duvivier**
Adding latest html for Consortium branch
Developer(s): Alice 
Are the code changes bit for bit, different at roundoff level, or more substantial? bit for bit
Is the documentation being updated with this PR? Y
If not, does the documentation need to be updated separately? N
"Documentation" includes information on the wiki and .rst files in doc/source/, 
which are used to create the online technical docs at https://cice-consortium.github.io/Icepack/ 
Please suggest code reviewers in the column at right. 
Other Relevant Details:

### CODE REVIEW

**Comment by duvivier** [comment]
Elizabeth, Note that you'll have to merge the pull request before the documentation shows up properly.

**Comment by eclare108213** [comment]
@duvivier Can you create a pdf for both the cice and icepack documentation, in their current states?  Please?

**Comment by eclare108213** [comment]
This is not quite right.  Section 4 is there, but it does not show up properly in the contents bar on the left-hand side of the page.

**Comment by duvivier** [comment]
Yes, I see the issue with the contents bar. I'll look it over asap (later tonight).

**Pull request merged**
