### PR TITLE
finalize 0-layer thermo and cesm ponds deprecation in Icepack

### PR DESCRIPTION
**Pull request by eclare108213**
- [x] Short (1 sentence) summary of your PR: 
Removes all ifdef options allowing 'undeprecation' of 0-layer thermo and cesm meltponds, and updates documentation
- [x] Developer(s): 
@eclare108213 @dabail10 
- [x] Suggest PR reviewers from list in the column to the right.
- [ ] Please copy the PR test results link or provide a summary of testing completed below.
    ENTER INFORMATION HERE 
- How much do the PR code changes differ from the unmodified code? 
    - [x] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on CICE or any other models?
    - [x] Yes
    - [ ] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [x] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/.)
    - [x] Yes
    - [ ] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [ ] No 
- [ ] Please provide any additional information or relevant details below:

### CODE REVIEW

**Comment by dabail10** [comment]
I think that hs0 is only used for the CESM ponds. hs0 is used to initialize the snow fraction in shortwave_dEdd_set_snow which is still called in the level ponds. However, with hs0 set to 0, the snow fraction will be set to 1 and then it is recomputed using hs1. Not sure if this subroutine should even be called.

**Comment by eclare108213** [comment]
@dabail10 I'll take a look, thanks for the insight.

**Comment by eclare108213** [comment]
I need to fix the formatting in the documentation, both here and in https://github.com/CICE-Consortium/CICE/pull/787

**Comment by eclare108213** [comment]
Unfortunately LANL is blocking my access to the Icepack documentation generated from this PR.  Could someone take a look at section 2.7 (there should be a new subsection called 'Snow fraction') and the bottom of the variable index, and let me know if they formatted okay?

**Comment by apcraig** [comment]
Everything looks good to me.  I tried to grab the pdf to send to you, but I think pdfs are only generated with a tag or something.

**Review by apcraig — APPROVED** [review]

**Comment by eclare108213** [comment]
I reverted the default/initial values of hs0 in both Icepack here and CICE https://github.com/CICE-Consortium/CICE/pull/787, but otherwise did not alter the documentation updates in either PR, pending resolution of https://github.com/CICE-Consortium/CICE/issues/635.  This PR partially addresses the confusing documentation called out in that PR.

**Comment by apcraig** [comment]
Test results for cheyenne intel are here, https://github.com/CICE-Consortium/Test-Results/wiki/icepack_by_hash_forks#ef0efc78666d7b7451eb86a76e2eb0e35f50156a.  Updated PR too.

**Pull request merged**
