### PR TITLE
Bug fixes for ISPOL and NICE test options. BFB physics

### PR DESCRIPTION
**Pull request by njeffery**
1. Adds missing parameters to init and write_parameters and init_zbgc
2. Corrects seg fault when using iron tracers
3. Fix to interpolation of 6 hourly data
4. Typo in forcing flag for NICE and parameter name
5. Adds nutrient data option for NICE
6. Corrections test configuration for NICE and bgc
7. Flag change to allow iron chemistry without DOC
8. Fixes for SKL bgc: corrects growth max & adds flag warning

[Remove this and add a short summary line]:
Developer(s):
Are the code changes bit for bit, different at roundoff level, or more substantial?
Is the documentation being updated with this PR? (Y/N)
If not, does the documentation need to be updated separately? (Y/N)
"Documentation" includes information on the wiki and .rst files in doc/source/, 
which are used to create the online technical docs at https://cice-consortium.github.io/Icepack/ 
Please suggest code reviewers in the column at right. 
Other Relevant Details:

### CODE REVIEW

**Comment by njeffery** [comment]
@eclare108213 :  Hopefully the conflicts should be minor.  I branched from master late last week.

**Comment by eclare108213** [comment]
@njeffery  The conflicts are coming from the refactoring of how constants are handled:  https://github.com/CICE-Consortium/Icepack/pull/83 
You should be able to pull the new changes from master into your fork, and you can look at the differences for configuration/driver/icedrv_forcing.F90 under the 'Files changed' tab at that pull request, to see where the new constants that you need are located or how to access them.   If you have questions about this, please ask @apcraig or me.  Thx

**Comment by eclare108213** [comment]
Here are the lines that are conflicting, in case the 'resolve conflicts' button isn't working for you.
<<<<<<< njeffery_NICE
      use icedrv_constants, only: nu_diag, nu_forcing, secday
      use icedrv_constants, only: c0, c1, c2, c10, c100, p5, c4
      use icedrv_constants, only: secday, Tffresh, qqqice, TTTice, rhos
=======
      use icedrv_constants, only: nu_diag, nu_forcing
      use icedrv_constants, only: c0, c1, c2, c10, c100, p5
>>>>>>> master

**Comment by apcraig** [comment]
I believe the resolution should be to use the "master" version, but maybe add c4 to the list.  Then, if there are any other new icepack constants that are needed, they should be set via a query to icepack_query_constants.  Nicole, if you need me to look at this, let me know.

**Comment by njeffery** [comment]
I resolved the conflicts.  Just needed to add c4 to what's already in master.  Do you see them as resolved?


________________________________

**Comment by apcraig** [comment]
It still shows as being conflicted.  Did you push your changes to njeffrey_NICE branch on your fork?

**Comment by njeffery** [comment]
After pulling,  my branch still has atm_climatological which uses tffresh, qqqice,  TTTice and rhos.  Should I keep the line...
use icedrv_constants, only: tffresh, qqqice, TTTice, rhos ?

**Comment by apcraig** [comment]
You should remove that line and give it a try.  If you need any of those constants and they are not already set, then you will need to define local variables and use icepack_query_constants to set them.  Again, happy to help if there are questions.

**Comment by njeffery** [comment]
559a5ea resolves the conflicts.

**Comment by apcraig** [comment]
I still see conflicts, did you push the change to your branch?  Looking at the files, icedrv_forcing still has this line,
 use icedrv_constants, only: secday, Tffresh, qqqice, TTTice, rhos

**Comment by njeffery** [comment]
Yes.  I pushed to my branch.  The line is needed for the thermo1 option.

________________________________

**Comment by apcraig** [comment]
That line has been replaced by a query to the icepack constants.  Please remove it and see if things still work.

**Comment by eclare108213** [comment]
I tried this.  The code compiles and runs and gets the same answers as in a baseline case from Nicole's branch.  However there are still a couple of bugs, so I'll let @njeffery fix them before merging.  Nicole, here's what to do, to get to where I was:

create baseline:
[eclare@pi-fe1 github]$ git clone -b njeffery_NICE https://github.com/njeffery/Icepack Icepack.NICE
[eclare@pi-fe1 github]$ cd Icepack.NICE
[eclare@pi-fe1 Icepack.NICE]$ icepack.create.case -ts base_suite -m pinto -testid n1 -bg nice.1
[eclare@pi-fe1 Icepack.NICE]$ cd base_suite.n1/
[eclare@pi-fe1 base_suite.n1]$ results.csh | grep FAIL
FAIL pinto_smoke_col_1x1_bgcISPOL_debug run
FAIL pinto_restart_col_1x1_bgcISPOL run-initial


[eclare@pi-fe1 github]$ git clone -b njeffery_NICE https://github.com/njeffery/Icepack Icepack.NICE2
[eclare@pi-fe1 github]$ cd Icepack.NICE2
[eclare@pi-fe1 Icepack.NICE2]$ git remote add upstream https://github.com/CICE-Consortium/Icepack
[eclare@pi-fe1 Icepack.NICE2]$ git pull upstream njeffery_NICE
[eclare@pi-fe1 Icepack.NICE2]$ emacs -nw configuration/driver/icedrv_forcing.F90
fix conflict by deleting 

        use icedrv_constants, only: secday, Tffresh, qqqice, TTTice, rhos

and adding c4 to the previous line
[eclare@pi-fe1 Icepack.NICE2]$ icepack.create.case -ts base_suite -m pinto -testid n2 -bc nice.1
[eclare@pi-fe1 Icepack.NICE2]$ cd base_suite.n2/
[eclare@pi-fe1 base_suite.n2]$ results.csh | grep FAIL
FAIL pinto_smoke_col_1x1_bgcISPOL_debug run
FAIL pinto_restart_col_1x1_bgcISPOL run-initial

**Comment by eclare108213** [comment]
@njeffery @chrisknewman 
Please follow up on the two tests that are failing, issue #96, thanks.

**Pull request merged**
