### PR TITLE
changes to default settings and interpolation bug fix

### PR DESCRIPTION
**Pull request by eclare108213**
Add ridging code test coverage as default, and fix bug in interp_coeff
Developer(s):  E Hunke
Are the code changes bit for bit, different at roundoff level, or more substantial?  The code is BFB but the tests are not because the namelist settings changed.
Is the documentation being updated with this PR? (Y/N)  N
If not, does the documentation need to be updated separately? (Y/N)  N
"Documentation" includes information on the wiki and .rst files in doc/source/, 
which are used to create the online technical docs at https://cice-consortium.github.io/Icepack/ 
Please suggest code reviewers in the column at right. 
Other Relevant Details:
Addresses issue #155 

- bug fix:  check that optional time offset is present in interpolation routine
- set tr_lvl = true in icepack_in
- set ocn_data_type = ‘SHEBA’ in icepack_in
- add bgcNICE to base_suite

Most comparisons fail because of the changes to the icepack_in namelists  (see https://github.com/CICE-Consortium/Test-Results/wiki/31933a6971.pinto.intel.180212.150805).
alt01 passes because it explicitly sets tr_lvl and ocn_data_type to the original values.  bgcNICE passes smoke and restart tests.

### CODE REVIEW

**Comment by apcraig** [comment]
alt01 is the only test that passes.  Otherwise, we are getting

Reading /p/work1/RASM_data/cice_consortium/Icepack_data/forcing/SHEB/open_clos_lindsay.dat                     

At line 1105 of file /p/home/apcraig/cice-consortium/icepack.eclare.defaultsets/configuration/driver/icedrv_forcing.F90 (unit = 15)
Fortran runtime error: Cannot open file '/p/work1/RASM_data/cice_consortium/Icepack_data/forcing/SHEBA/open_clos_lindsay.dat': No such file or directory

So, we need to figure out how download that file as part of travis.  We'll need to add some logic upfront to grab and/or grab/cache that file.  Up to now, we have not needed input data for icepack.

**Comment by anders-dc** [comment]
I'd be glad to help with this. Could you point me to the command used to fetch the file?

**Comment by apcraig** [comment]
Thanks anders.  What we do is download the file as a preprocessing step manually and put it in a local area to reuse it.  Would it be possible to cache this file somewhere on travis?  What we'd like is a top level directory that is static and then we populate dirs/files under that.  Could something like that be done in the cloud?

**Comment by eclare108213** [comment]
How does travis run the other tests without forcing data?  Does it only test using the hard-coded defaults?

**Comment by anders-dc** [comment]
@eclare108213 Yes, so far the travis builds are fetching nothing outside of this repository.

**Comment by apcraig** [comment]
@eclare108213, I believe that is true.  Right now, Icepack needs no input data that is not carried either in source code or in the repo already.  At least, that's how all the tests seem to be running on travis and I assume elsewhere.  We should confirm.

**Comment by anders-dc** [comment]
@apcraig Great, we can fetch the datafiles in a `before_script` target, and [cache the directory where we store them](https://docs.travis-ci.com/user/caching/#Arbitrary-directories).

Could you provide me with a url to the data files so I can set this up?

**Comment by eclare108213** [comment]
We could set default values and create a special set of tests for travis with a new ocn_data_type, say 'travis-conv'.  This might not work well because the ridging can easily get out of physical bounds and crash the code.

**Comment by apcraig** [comment]
@eclare108213, Ultimately, we will want to have input data on travis to do CICE testing.  So we might as well just get it working now.  We can also have other travis namelist settings, that's fine too.

@anders-dc, if you look here, https://github.com/CICE-Consortium/Icepack/wiki/Testing-Icepack, under Forcing Data, you'll see pointers to the ftp site.  The gz file is probably not up to date.  What we want to do is duplicate the entire directory/file structure under "archive/Model-Data/CICE" on travis if possible.  That will include both Icepack and CICE files, but we will need both eventually.  And we will need to know how to add new datasets when they arise.  Let me know if that makes sense.

**Comment by anders-dc** [comment]
@apcraig It will take some hours before I have the data mirrored to my computer for inspection. Any of the files under [ftp.cgd.ucar.edu/archive/Model-Data/CICE] that I can safely ignore? From your previous comments I guess `Icepack_data.tar.gz` is safe to skip. What about `CICE_data_all.tar.gz`? Can you tell me which archive contains the `forcing/SHEBA/open_clos_lindsay.dat` file?

**Comment by eclare108213** [comment]
For Icepack testing, you only need Icepack_data.tar.gz, which is small.  The SHEBA data file should be in there — @dabail10 said he’d put it on the ftp.  You can ignore the (big) cice data files for now.
e

**Comment by anders-dc** [comment]
Perfect, thank you @eclare108213

**Comment by apcraig** [comment]
One other data point.  in env.travis-ci, you'll see

setenv ICE_MACHINE_INPUTDATA ~/ICEPACK_INPUTDATA

that defines the top level directory for the input data.  Please set this as needed to identify that location on travis.  Hopefully, that will work ok.  if not, let me know.

**Comment by anders-dc** [comment]
Thanks both, see #165.

**Comment by apcraig** [comment]
I forced a retest on travis after PR #165.

**Comment by anders-dc** [comment]
Hm, in order to rerun the tests with the changes in #165, I think they have to be merged from the master branch of CICE-Consortium/Icepack to this branch (eclare108213:defaultsets). @eclare108213: I think you can do this by running `git pull upstream master && git push` to this branch.

**Comment by apcraig** [comment]
travis failed again.  It looks like it didn't pickup the latest PR.  I assume we'd have to merge master onto the branch and then push.  That should pickup the latest changes and also trigger travis.

**Comment by eclare108213** [comment]
fingers crossed!

**Comment by anders-dc** [comment]
https://github.com/CICE-Consortium/Test-Results/wiki/acb056e1e0.travisCI.gnu.180212.194943

**Comment by apcraig** [comment]
same result as before.

**Comment by anders-dc** [comment]
I'm having a hard time deciphering the test output. Do we know if the external data still is causing the tests to fail?

**Comment by apcraig** [comment]
It looks like the untar is happening, I can see it in the log file.  But I can't tell what's failing.  It is working for me on gordon with the new dataset available.  I'm looking.

**Comment by anders-dc** [comment]
It seems that it would be valuable to be able to inspect the `runlog` files. What if we `cat` them to stdout during the travis runs?

**Comment by apcraig** [comment]
I was thinking the same thing.  I was thinking if a test fails, to tail -200 the log file.  But what you propose would also be fine.  Can we do that just for travis?

**Comment by apcraig** [comment]
Can we modify this PR to debug the travis stuff?

**Comment by anders-dc** [comment]
I will add a line in the `after_failure` hook which loops over the runlogs and prints them. I do not think there is an easy way to exclusively print runlogs from failed tests without modifying your code.

**Comment by eclare108213** [comment]
Whatever you need.  We can also hold these changes until after the release, add a test to base_suite to cover the ridging code, and not include it in the travis suite.  I'd prefer we have travis test the ridging too, if possible.

**Comment by apcraig** [comment]
@anders-dc, so you want to merge the defaultsets branch into your branch #166  for testing?  we can continue to do this via multiple PRs but it might be easier to do it via 1 PR.

**Comment by anders-dc** [comment]
@apcraig I think a merge is necessary to debug why Travis is having issues with @eclare108213's changes in this PR.

**Comment by apcraig** [comment]
ok, i just merged #166.  @eclare108213 can you do another pull/push.

@anders-dc i meant do say "do you", not "so you" above.  I think you could pull the defaultsets branch into a branch in your fork and have a copy of these changes and control your own PR.  We can then decide whether to cancel this PR and just merge yours or whether to merge this one then yours, either way should be the same.  Just takes @eclare108213 out of the loop during debugging.

**Comment by anders-dc** [comment]
I’ll be back working on this in a couple of hours

**Comment by apcraig** [comment]
thanks @anders-dc .  in the mean time, i'm testing on gordon with 4 compilers.

**Comment by apcraig** [comment]
I've tested this on gordon with 4 different compilers.  I am getting 3 failures (in addition to many different answers).

FAIL gordon_gnu_smoke_col_1x1_bgcISPOL_debug run
  fails in update_hbrine with exp error, should be fixed with PR #158
FAIL gordon_gnu_smoke_col_1x1_bgcNICE_debug run
  fails in update_hbrine with exp error, should be fixed with PR #158
FAIL gordon_gnu_smoke_col_1x1_debug_run1year_thermo1 run
  fails in an arithmetic exception in icepack_mechred:ridge_shift

I propose we merge this, push other PRs, and then work on the mechred error and travis issue separately.  Both have to be fixed before we release.  

@eclare108213, please let me know if you agree and if so, I will merge.

**Comment by eclare108213** [comment]
I agree, please merge.
e

________________________________

**Comment by dabail10** [comment]
Is the last failure related to my changes in icepack_mechred.F90 for the SHEBA option? What line is the failure?

**Comment by anders-dc** [comment]
@dabail10: I am currently digging in to the exact cause of the failures on Travis. I expect these issues to be related to some Travis-specific setup, since the tests are reported to pass in other environments. If not, I will open a separate ticket.

**Comment by apcraig** [comment]
The one case still to debug is failing at
icepack_mechred.F90:1456
I have that case in front of me and will work on it.  Separately, @anders-dc is working on the travis stuff.  @anders-dc, I am going to merge this now, please create a new PR from master.

**Pull request merged**
