### PR TITLE
Readthedocs

### PR DESCRIPTION
**Pull request by duvivier**
Updating documentation to include readthedocs.org stuff

Developer(s): Alice DuVivier
Are the code changes bit for bit, different at roundoff level, or more substantial? bit for bit
Is the documentation being updated with this PR? (Y/N) Yes
If not, does the documentation need to be updated separately? (Y/N) No
"Documentation" includes information on the wiki and .rst files in doc/source/, 
which are used to create the online technical docs at https://cice-consortium.github.io/Icepack/ 
Please suggest code reviewers in the column at right. 
Other Relevant Details:
- You can see the updated documentation at my readthedocs.org personal site: https://readthedocs.org/projects/icepack/
-Added Collins reference from Issue #73 
-Added documentation to HTML for how to use readthedocs.org for issue #185
-Removed extraneous documents from /docs/ directory from issue #186 
- I updated README.md to reflect the new documentation location. I've double checked and the wiki links are correct.
-I also updated the PR template since it referenced the old documentation site. I also tried to better highlight the sections people need to answer since the big block of text can run together a bit.

### CODE REVIEW

**Comment by duvivier** [comment]
@apcraig @eclare108213 I think if this all looks good we can soon delete the gh-pages branch. I want you both to look through this all carefully before we do that though. But I'd suggest perhaps waiting for v1.0.1 release until after gh-pages has been deleted.

**Comment by duvivier** [comment]
It might also be nice to add the green "docs passing" badge (see here: https://github.com/rtfd/readthedocs.org under README.rst) to the PR process.  Thoughts on how to do this?

**Comment by duvivier** [comment]
No, you can choose any username you want. I think it's easiest to have them match, but ultimately that would be up to the user. I've clarified this as well as the USERNAME placeholder in the docs. I also modified the link to the workflow guide to point to the CICE wiki.

**Comment by eclare108213** [comment]
sorry to be so nit-picky, but there's still at least one reference to the google doc, line 164 of dg_documentation...

**Comment by duvivier** [comment]
It's not nitpicky, it is good to be consistent and I'd missed that one.

**Comment by eclare108213** [comment]
Thanks Alice.  I'll merge this one, and we can fix other things as we find them.  There's always more to do....

**Pull request merged**
