### PR TITLE
Pr template

### PR DESCRIPTION
**Pull request by duvivier**
Adding pull request template for Icepack repo as per discussion with Elizabeth. Matches that in CICE repo.
Developer(s): Alice DuVivier
Updated documentation (Y/N): N
Results (bit for bit, roundoff, climate changing): bit for bit
Code review:
Other Relevant Details:

### CODE REVIEW

**Comment by duvivier** [comment]
Tony, Elizabeth,
I just noticed more than the single file I'd changed is listed as changes. I thought I'd done a merge with the current master branch but it looks like maybe that didn't work properly. The only thing that needs to be merged as part of this PR is the .github directory with the PULL_REQUEST_TEMPLATE. Does it make sense to just merge this or should I set up a new PR?

**Comment by apcraig** [comment]
@duvivier.  The issue of showing a bunch of diffs that are already in the master is a known github feature (problem?).  I am thinking about changing the git workflow document.  Please try the following (or an equivalent).  In a sandbox of your icepack fork and PR_template branch (github.com/duvivier/icepack, git checkout PR_template),

git remote add upstream https://github.com/CICE-Consortium/Icepack
git pull --rebase upstream master
git push -f origin PR_template

Lets see if that fixes the PR.  If so, then I'll update the documentation to encourage this approach when merging upstream updates to a branch.

**Comment by duvivier** [comment]
Tony, I just followed the procedure you suggested. I'm not seeing that it fixed things, but maybe you'll see something different on your end. Let me know how best to proceed from here.

**Comment by apcraig** [comment]
Alice, I'm looking at your changes a little more closely.  It looks like the diffs in the PR are actually all new things.  It doesn't look like the other 51 file changes in your PR are in the icepack repo yet.  For instance, I see no files under doc/source/figures, https://github.com/CICE-Consortium/Icepack/tree/master/doc/source.  Are you sure you pushed those to the consortium master before now?

**Comment by duvivier** [comment]
Hum, that suggests that I accidentally merged the documentation changes that Elizabeth and I are working on with the PR request. At this point I think we should close this PR and I will try again with the PR after I sort out the rebasing, etc. Does that make sense?

**Pull request closed without merging**
