### PR TITLE
Isotope

### PR DESCRIPTION
**Pull request by dabail10**
#91  PR checklist
- [X] Short (1 sentence) summary of your PR: 
This PR adds the water isotope tracers to icepack. Comes from the CESM code.
- [X] Developer(s): 
 David Bailey (dabail10)
- [X] Suggest PR reviewers from list in the column to the right.
- [X] Please copy the PR test results link or provide a summary of testing completed below.
 https://github.com/CICE-Consortium/Test-Results/wiki/64a2cee85b.izumi.nag.190904.221343
https://github.com/CICE-Consortium/Test-Results/wiki/64a2cee85b.izumi.intel.190904.221343
https://github.com/CICE-Consortium/Test-Results/wiki/a5449f5207.izumi.gnu.190905.155549
https://github.com/CICE-Consortium/Test-Results/wiki/a5449f5207.izumi.pgi.190905.200002
- How much do the PR code changes differ from the unmodified code? 
    - [X] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on CICE or any other models?
    - [x] Yes
    - [ ] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [X] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/.)
    - [ ] Yes
    - [X] No, does the documentation need to be updated at a later time?
        - [X] Yes
        - [ ] No 
- [X] Please provide any additional information or relevant details below:
This includes the water isotope tracers. They are very similar to the aerosol tracers, but not like the zaero tracers. I would eventually like to treat the isotopes the same way as the zaero tracers, but we need the current implementation for the CESM. Results are bfb with tr_iso = .false., but fail the restart comparison with tr_iso = .true. This is because the isotopes are needed in the restart files. The ice_diag ascii files are identical. This will address #248

### CODE REVIEW

**Comment by apcraig** [comment]
One issue is that it looks like at least one (maybe more) interface (icepack_atm_boundary) is modified which will break CICE until CICE is updated and tested.  If we push this to master, we cannot test any icepack changes in CICE and icepack master will be broken with respect to CICE.  I think my preference would be that CICE modifications be carried out before we merge this PR.  This will ensure that the new icepack mods are working in CICE and it will not block other changes to icepack moving forward.

This is one area where the current icepack interfaces are not that great, extensibility.  And by the way, I still don't know how/if we should proceed with any icepack interface refactor at this point.  But that's a separate issue.

**Comment by dabail10** [comment]
Excellent point. I will modify the above that this requires a CICE PR as well.

**Comment by apcraig** [comment]
You can ignore this comment, just testing something.

**Comment by apcraig** [comment]
@dabail10.  Even if this is not quite ready for usage, I still have the same question as in September.  If we merge this now/soon, will be unable to update CICE with new Icepacks due to interface changes?  Can we have a CICE PR that addresses this issue?  We do not want to make the Icepack master unusuable in CICE for any extended period of time.  It's fine if it's a couple days and we have a plan to get past it.  But I worry that's not the case here.

**Comment by dabail10** [comment]
I am doing extensive testing with both Icepack and CICE updated to master. This should be ready soon.

**Comment by eclare108213** [comment]
This PR is being replaced by #307, so closing it now.

**Pull request closed without merging**
