### PR TITLE
Remove yellowstone and fix some of the documentation.

### PR DESCRIPTION
**Pull request by dabail10**
[Remove this and add a short summary line]:
Developer(s): D. Bailey
Are the code changes bit for bit, different at roundoff level, or more substantial? bfb
Is the documentation being updated with this PR? (Y/N) Y
If not, does the documentation need to be updated separately? (Y/N) N
"Documentation" includes information on the wiki and .rst files in doc/source/, 
which are used to create the online technical docs at https://cice-consortium.github.io/Icepack/ 
Please suggest code reviewers in the column at right. 
Other Relevant Details:

### CODE REVIEW

**Comment by dabail10** [comment]
Oh, I see. The problem is that the italic notation is not recognized as an actual section and hence the references to them were not working. So, you object to a subsection number of 2.7.3.2.1? If not, we could use a line of carats (^) to designate the next level.

**Comment by eclare108213** [comment]
Carats would be fine too.  I think there are some other subsections that are just italicized in other parts of the docs.
e

**Comment by dabail10** [comment]
The italicized sections are fine if you don't need to reference them.

Dave

**Comment by dabail10** [comment]
Ok. I have done the subsections at this level all with lines of carats for consistency.

**Pull request merged**
