### PR TITLE
Update CDash Implementation

### PR DESCRIPTION
**Pull request by mattdturner**
This PR updates the CDash implementation, adding ICE_MACHINE_QSTAT, and always copying CTest files to the suite directory
Developer(s):  Matt Turner
Are the code changes bit for bit, different at roundoff level, or more substantial? bit-for-bit
Is the documentation being updated with this PR? (Y/N) Y
If not, does the documentation need to be updated separately? (Y/N)
"Documentation" includes information on the wiki and .rst files in doc/source/, 
which are used to create the online technical docs at https://cice-consortium.github.io/Icepack/ 
Please suggest code reviewers in the column at right. 
Other Relevant Details:

### CODE REVIEW

**Comment by eclare108213** [comment]
This almost worked.  

           icepack.create.case -ts base_suite -testid tweaks -m pinto -report

runs and submits the report, but I don't see it at
https://my.cdash.org/index.php?project=myICEPACK
What should I look for, to find out what happened?

55 of 56 tests PASSED
1 of 56 tests FAILED
0 of 56 tests PENDING
build name = Linux-x86_64-intel17.0.4-3b7ab44
source directory = /turquoise/usr/projects/climate/eclare/CICE.v6.0/github/Icepack.cdash_tweaks/base_suite.tweaks
Submit Succeeded
 
icepack.create.case done
 
[eclare@pi-fe1 Icepack.cdash_tweaks]$ date
Sat Jan  6 12:04:44 MST 2018

**Comment by mattdturner** [comment]
The CTest logs are found in ./Testing/Temporary/Last<Submit,Tests,TestFailed>*.log.  Although, since it said that the submit succeeded I am not sure how much useful information will be in the logs.

**Comment by eclare108213** [comment]
Here is the content of LastSubmit_20180106-1900.log.  How does the system know to send the output to CDash?  I searched for the strings Dash, dash, and http in the Test.xml file too, not turning up anything.

Upload files:
0       Test.xml
Using drop method: http
        Upload file: /turquoise/usr/projects/climate/eclare/CICE.v6.0/github/Icepack.cdash_tweaks/base_suite.tweaks/Testing/20180106-1900/Test.xml to pi-fe1.lanl.gov___Linux-x86_64-intel17.0.4-3b7ab44___20180106-1900-Experimental___XML___Test.xml
   Submission successful

**Comment by mattdturner** [comment]
I don't see anything wrong there, but it also doesn't give very much information.  

The steer.cmake script calls `ctest_submit`, which is what tells CTest to submit the results to the `CTEST_DROP_SITE` defined in `CTestConfig.cmake`.  However, I am not sure what CTest does behind the scenes when submitting to CDash.

**Comment by eclare108213** [comment]
Now the CDash site shows test results submitted from pi-fe1 on Saturday, but it lists 9 tests having failed when there was only one that failed.  The eight others that CDash lists are 'compare' cases that I did not run or try to compare with in this test.  Should reporting only be allowed if a comparison is being done?

**Comment by mattdturner** [comment]
I suppose we could only submit the results to CDash if a comparison is being done.  I'm not sure if reporting the lack of a comparison as a failure is a bad thing, though.  If we will be using the CDash reporting as a means to ensure that code changes do not break anything, reporting these as failures will alert us that the entire testing process was not fulfilled.

**Pull request merged**
