### PR TITLE
Add gnuplot to the conda environment

### PR DESCRIPTION
**Pull request by dabail10**
For detailed information about submitting Pull Requests (PRs) to the CICE-Consortium,
please refer to: <https://github.com/CICE-Consortium/About-Us/wiki/Resource-Index#information-for-developers>


## PR checklist
- [X] Short (1 sentence) summary of your PR: 
Just adds gnuplot to the conda environment.
- [X] Developer(s): 
dabail10 (D. Bailey)
- [X] Suggest PR reviewers from list in the column to the right.
- [X] Please copy the PR test results link or provide a summary of testing completed below.
- 
Tested on my Mac conda environment.

[cgdm-hurricane:~/icepack-tutorial/icepack_master] dbailey% conda env create -f configuration/scripts/machines/environment.yml
Channels:
 - conda-forge
Platform: osx-64
Collecting package metadata (repodata.json): done
Solving environment: done

Downloading and Extracting Packages:
                                                                                                                                    
Preparing transaction: done                                                                                                         
Verifying transaction: done                                                                                                         
Executing transaction: done                                                                                                         
#                                                                                                                                   
# To activate this environment, use                                                                                                 
#                                                                                                                                   
#     $ conda activate icepack                                                                                                      
#                                                                                                                                   
# To deactivate an active environment, use                                                                                          
#                                                                                                                                   
#     $ conda deactivate                                                                                                            
                                                                                                                                    
[cgdm-hurricane:~/icepack-tutorial/icepack_master] dbailey% conda activate icepack                                                  
(icepack) [cgdm-hurricane:~/icepack-tutorial/icepack_master] dbailey% which gnuplot
/Users/dbailey/miniconda3/envs/icepack/bin/gnuplot                               
- How much do the PR code changes differ from the unmodified code? 
    - [X] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on CICE or any other models?
    - [ ] Yes
    - [X] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [X] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/.)
    - [ ] Yes
    - [X] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [X] No 
- [X] Please provide any additional information or relevant details below:
This fix allows the timeseries.csh script to be used for Icepack standalone runs.

### CODE REVIEW

**Review by phil-blain — APPROVED** [review]
Thanks Dave!

**Comment by dabail10** [comment]
I'm not sure why this is failing. It seems to be building the conda environment correctly ...

**Comment by apcraig** [comment]
Could you comment out the gnuplot addition then push that change.  Lets see if that fails ghactions.  If not, turn it back on then resubmit, lets see if the failure is a problem in ghactions or gnuplot.  It seems to be failing on debug+histcdf.  I wonder if adding gnuplot is messing with the netcdf somehow.

**Comment by apcraig** [comment]
Did you build and run the icepack test suite on your mac or just verify that gnuplot was part of the environment?

**Comment by apcraig** [comment]
Looks like ghactions may have changed and now things are not working, see #484.  Occurs far too often.  Let me look into it.

**Comment by apcraig** [comment]
@dabail10, if you get a chance, can you run the io_suite on your mac laptop and let me know if you get any failures.  I'm having trouble duplicating this error with my mac env (older OS), and I'm not getting much useful info from the log files on github actions.  I'm updating my conda env now and will try a laptop shortly to see if I can make any progress.  Just wondering if a newer mac OS which you might have will pick this up.

**Comment by apcraig** [comment]
I updated my conda env on my mac desktop, I'm seeing the failure now.  Will try to debug.  @dabail10, don't need anything from you at the moment.

**Comment by dabail10** [comment]
This worked on my mac:

#------- 
#repo = origin http://github.com/ESCOMP/Icepack (push)
#bran = On branch main
#hash = f6ff8f7c4d4cb6feabe3651b13204cf43fc948e3
#hshs = f6ff8f7c4d
#hshu = Tony Craig <apcraig@users.noreply.github.com>
#hshd = Fri Nov 17 09:22:49 2023 -0800
#suit = io_suite
#date = 2024-02-29
#time = 21:05:13
#mach = conda
#user = dbailey
#vers = ICEPACK_1.4.0
#------- 
#---
PASS conda_macos_restart_col_1x1_debug_ionetcdf build
PASS conda_macos_restart_col_1x1_debug_ionetcdf initialrun
PASS conda_macos_restart_col_1x1_debug_ionetcdf run 
PASS conda_macos_restart_col_1x1_debug_ionetcdf test 
#---
PASS conda_macos_smoke_col_1x1_diag1_ionetcdf_run1year build
PASS conda_macos_smoke_col_1x1_diag1_ionetcdf_run1year run
PASS conda_macos_smoke_col_1x1_diag1_ionetcdf_run1year test
#---
PASS conda_macos_restart_col_1x1_debug_histcdf_ionetcdf build
PASS conda_macos_restart_col_1x1_debug_histcdf_ionetcdf initialrun
PASS conda_macos_restart_col_1x1_debug_histcdf_ionetcdf run 
PASS conda_macos_restart_col_1x1_debug_histcdf_ionetcdf test 
#---
PASS conda_macos_smoke_col_1x1_diag1_histcdf_ionetcdf_run1year build
PASS conda_macos_smoke_col_1x1_diag1_histcdf_ionetcdf_run1year run
PASS conda_macos_smoke_col_1x1_diag1_histcdf_ionetcdf_run1year test
#---
PASS conda_macos_restart_col_1x1_debug_ionetcdf_restcdf build
PASS conda_macos_restart_col_1x1_debug_ionetcdf_restcdf initialrun
PASS conda_macos_restart_col_1x1_debug_ionetcdf_restcdf run 
PASS conda_macos_restart_col_1x1_debug_ionetcdf_restcdf test 
#---
PASS conda_macos_smoke_col_1x1_diag1_ionetcdf_restcdf_run1year build
PASS conda_macos_smoke_col_1x1_diag1_ionetcdf_restcdf_run1year run
PASS conda_macos_smoke_col_1x1_diag1_ionetcdf_restcdf_run1year test
#---
PASS conda_macos_restart_col_1x1_debug_histcdf_ionetcdf_restcdf build
PASS conda_macos_restart_col_1x1_debug_histcdf_ionetcdf_restcdf initialrun
PASS conda_macos_restart_col_1x1_debug_histcdf_ionetcdf_restcdf run 
PASS conda_macos_restart_col_1x1_debug_histcdf_ionetcdf_restcdf test 
#---
PASS conda_macos_smoke_col_1x1_diag1_histcdf_ionetcdf_restcdf_run1year build
PASS conda_macos_smoke_col_1x1_diag1_histcdf_ionetcdf_restcdf_run1year run
PASS conda_macos_smoke_col_1x1_diag1_histcdf_ionetcdf_restcdf_run1year test

Descriptors:
 PASS - successful completion
 COPY - previously compiled code was copied for new test
 MISS - comparison data is missing
 PEND - status is undetermined; test may still be queued, running, or timed out
 FAIL - test failed

28 measured results of 28 total results
28 of 28 tests PASSED
0 of 28 tests PENDING
0 of 28 tests MISSING data
0 of 28 tests FAILED

**Comment by apcraig** [comment]
OK, it did for me too until I updated to the latest conda env.

You can update your conda env by doing something like

  conda env create -f configuration/scripts/machines/environment.yml --force

from the top of cice or icepack.

I've decided this is a compiler issue.  It's failing in nf90_create when debug is on, in particular with ffpe-trap=invalid.  So, I'm going to turn off that debug flag.  Will update #484 with this fix, we can merge that, then we can restart ghactions testing on this PR.

**Comment by apcraig** [comment]
@dabail10, can you update your branch from main then push the update.  That should allow ghactions to run.

**Comment by dabail10** [comment]
I changed a comment line and committed and pushed, but it did not restart GHActions.

**Comment by dabail10** [comment]
I just commented out the gnuplot line and comitted / pushed and still not working.

**Comment by apcraig** [comment]
ghactions ran and passed.  Can you update the branch again with gnuplot.

**Pull request merged**
