### PR TITLE
Add Tutorial to User Guide as Appendix

### PR DESCRIPTION
**Pull request by apcraig**
## PR checklist
- [X] Short (1 sentence) summary of your PR: 
    Add Tutorial to User Guide as Appendix
- [X] Developer(s): 
    apcraig
- [X] Suggest PR reviewers from list in the column to the right.
- [X] Please copy the PR test results link or provide a summary of testing completed below.
    No testing done, only documentation changes, reviewed documentation via readthedocs
- How much do the PR code changes differ from the unmodified code? 
    - [X] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on CICE or any other models?
    - [ ] Yes
    - [X] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [X] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/.)
    - [X] Yes
    - [ ] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [ ] No 
- [X] Please document the changes in detail, including _why_ the changes are made.  This will become part of the PR commit log.

Add the tutorial to the user guide as an appendix.  Allows for easy links into the rest of the documentation and gives it a permanent and accessible home.  The icepack variable name table was also moved to the new appendix section.

### CODE REVIEW

**Review by dabail10 — APPROVED** [review]
Looks great!

**Comment by apcraig** [comment]
Should the appendices be after or before the references?

**Comment by dabail10** [comment]
> Should the appendices be after or before the references?

I don't really have a preference.

**Comment by eclare108213** [comment]
These appendices make most sense before the references, in my opinion.  This is awesome, thank you very much.  I do (as usual) have quite a few little tweaky grammar kinds of things.  I'll clone the branch...

**Comment by apcraig** [comment]
We could also get rid of the formal rst subsections (6.2.1, 6.2.2, etc) and just make those bolded (or similar) headings in the tutorial.  That would remove them from the table of contents.  I'm not sure they each deserve a separate rst section/heading.

**Comment by eclare108213** [comment]
I like how visible the subsections are in the text, and I don't mind them showing up in the table of contents.
I'm attempting to edit/commit directly in github.  Let me know if you think that's a bad idea... seems like it will work.

**Comment by apcraig** [comment]
editing and committing in github is fine.  individual commits are created just like if you did it in a sandbox.

**Comment by apcraig** [comment]
Everything looks good to me.  Any other comments/changes?

**Review by eclare108213 — APPROVED** [review]
This is great, thank you!

**Pull request merged**
