### PR TITLE
Isotopes for Icepack

### PR DESCRIPTION
**Pull request by eclare108213**
This PR is not yet ready to be merged - further review, testing and documentation is required.

- [x] Short (1 sentence) summary of your PR: 
Addition of isotope diagnostics following @dabail10's implementation for CESM.
- [x] Developer(s): 
    @dabail10 @eclare108213 @apcraig 
- [x] Suggest PR reviewers from list in the column to the right.
- [ ] Please copy the PR test results link or provide a summary of testing completed below.
Initial tests by @apcraig looked okay
(see https://github.com/eclare108213/Icepack/pull/1) 
but this needs to be reconfirmed.
- How much do the PR code changes differ from the unmodified code? 
    - [x] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on CICE or any other models?
    - [ ] Yes
    - [x] No
- Does this PR add any new test cases?
    - [x] Yes
    - [ ] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/.)
    - [x] Yes
    - [ ] No, does the documentation need to be updated at a later time?
        - [x] Yes
        - [ ] No 
Documentation for the interfaces is currently here but the isotope physics and code description needs to be added.
- [x] Please provide any additional information or relevant details below:

I will add the associated CICE PR shortly.  Both this PR and the CICE one need @dabail10 's scrutiny to make sure the results are correct.

### CODE REVIEW

**Comment by apcraig** [comment]
I'm happy to do some additional testing when it's appropriate.  Just let me know how I can help.  It sounds like the first step might be review and testing of the isotope implementation by @dabail10.  Then when that is ready, some further technical testing with full test suites on multiple machines/compilers?  If that's not the best process, let me know.  I assume this goes for both the Icepack and CICE mods.

**Comment by eclare108213** [comment]
Yes, both codes need review and testing.  I'm trying to test them both against the master baselines now, to see what still needs work besides cice restarts.  Here's my plan:

1. create baselines - still working on this (need gx3 JRA data)
2. regression test of cice v6.1.1 with iiso2 against v611, isotopes OFF - in progress
3. regression test of iiso2 against v121, isotopes ON - in progress
4. cice testing/debugging with isotopes ON

@dabail10 please take a look at the code at any point in this process.  It's already producing what I think are reasonable looking results, but it definitely needs your experienced eyeballs.

@apcraig if you'd like to jump in with the regression testing, I'd be grateful!
Thanks.

**Comment by apcraig** [comment]
Sounds good, I will start some of the regression testing on multiple machines/compilers as well.

**Comment by dabail10** [comment]
Sorry I haven't had time to look at this. I will put aside a couple hours tomorrow on this.

Dave

**Comment by eclare108213** [comment]
Icepack v1.2.1 baseline:
https://github.com/CICE-Consortium/Test-Results/wiki/edb8c34593.badger.intel.20-03-29.115033

regression test of iiso2 against v121 with isotopes turned off:
https://github.com/CICE-Consortium/Test-Results/wiki/cb7aa7b255.badger.intel.20-03-29.120228

**Comment by apcraig** [comment]
Full test suites on conrad with 4 compilers are [here](https://github.com/CICE-Consortium/Test-Results/wiki/icepack_by_hash_forks#b408817a20f6b6ae821ad734103ea4c0ac8814b3) (#b408817a).  What you see is that everything passes fine except 7 intel tests are failing regression tests.  This is the same result as tests from about a month ago, and I attribute this to compiler optimization with intel.  Other compilers are bit-for-bit and all intel debug tests are bit-for-bit.  We could look into this further, but I'm not convinced it's needed.  I am just running the test suite out of the box.

**Comment by eclare108213** [comment]
Great, thanks @dabail10.  I've done as much with the indexing as I plan to, for the isotopes PRs.  We can continue to work on that separately.  We also can merge this as it is and make an issue to track down the conservation error later.

**Comment by dabail10** [comment]
I am running a CICE case now with history output to verify the science changes there. These will have to be merged together.

**Comment by apcraig** [comment]
We should probably close #275 when it's appropriate.

**Comment by eclare108213** [comment]
The documentation needs to be updated before this is merged.  @dabail10 you can submit a PR to my fork, or make the changes in your fork and I'll grab them.  We'll need this for CICE too.

**Comment by eclare108213** [comment]
I think this PR is ready to merge, but the readthedocs check isn't finished (after 3+ hours).  Is it possible to relaunch that?

**Comment by eclare108213** [comment]
I changed the python version in my readthedocs account from 2.x to 3.x, and then the build succeeded.  I didn't see a way to relaunch buildthedocs from here, so I had to commit a minor change in one of the files (which needed to be done anyhow), but that means that I'm not 100% sure whether the change to 3.x is what fixed the build problem here - I'm 99% sure.  I guess I shouldn't be surprised that a PR would use the settings in the user's account rather than the settings for the main repository being merged into.  Regardless, we might want to change the [documentation workflow](https://github.com/CICE-Consortium/About-Us/wiki/Documentation-Workflow-Guidance) to tell people to use 3.x instead of 2.x.

This PR is ready to merge.

**Comment by apcraig** [comment]
@eclare108213, I had a quick look around and think everything is fine.  Why don't you merge this PR when you're ready.

**Comment by apcraig** [comment]
I ran full test suites on several platforms today with the current master.  https://github.com/CICE-Consortium/Test-Results/wiki/icepack_by_hash#1ae044604498b8d268df6c577556d22d2baa7758.  Results are as expected.

**Pull request merged**
