### PR TITLE
doc: change URL of a reference to avoid '%' character

### PR DESCRIPTION
**Pull request by TillRasmussen**
For detailed information about submitting Pull Requests (PRs) to the CICE-Consortium,
please refer to: <https://github.com/CICE-Consortium/About-Us/wiki/Resource-Index#information-for-developers>

## PR checklist
- [ ] Short (1 sentence) summary of your PR: 
    sphinxbuild complains if url includes %.  Changed url
- [ ] Developer(s): 
    Trasmussen
- [ ] Suggest PR reviewers from list in the column to the right.
 @eclare108213 @apcraig 
- [ ] Please copy the PR test results link or provide a summary of testing completed below.
    sphinx build work
- How much do the PR code changes differ from the unmodified code? 
    - [ ] bit for bit
    - [ ] different at roundoff level
    - [ x] more substantial (could not create doc for latex
- Does this PR create or have dependencies on CICE or any other models?
    - [ ] Yes
    - [x ] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [x ] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/.)
    - [x ] Yes
    - [ ] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [ ] No 
- [ ] Please provide any additional information or relevant details below:

This is needed to make the latex target of the documentation Makefile work

### CODE REVIEW

**Comment by phil-blain** [comment]
Hi Till!

I think this should be a single commit PR. Could you rebase on the latest `master` and squash both commits into one ? this would make for a clearer history (and would remove the three merge commits that are appearing here).

Also, since the title of the PR becomes the commit message on `master` when the PR is merged, could you make it a little more explicit ? Maybe "doc: change URL of a reference to avoid '%' character", and explain in the commit message that this is needed to make the  `latex` target of the documentation Makefile work?

Thanks :)

**Review by dabail10 — APPROVED** [review]

**Review by eclare108213 — APPROVED** [review]

**Comment by eclare108213** [comment]
I don't think @TillRasmussen needs to squash the 2 commits, since @apcraig or I can do that we merge.  It would be helpful to change the title, though.

**Comment by apcraig** [comment]
I updated the title and added a comment as suggested by @phil-blain.  Merging now.  Thanks!

**Comment by TillRasmussen** [comment]
Ok, thanks

fre. 23. okt. 2020 21.15 skrev Tony Craig <notifications@github.com>:

**Pull request merged**
