### PR TITLE
Codecleanup2

### PR DESCRIPTION
**Pull request by eclare108213**
Cleaning up the code for readability.  Fixed ISPOL restart problem.
Developer(s):  E Hunke
Are the code changes bit for bit, different at roundoff level, or more substantial?  BFB
Is the documentation being updated with this PR? (Y/N)  N
If not, does the documentation need to be updated separately? (Y/N)  N
"Documentation" includes information on the wiki and .rst files in doc/source/, 
which are used to create the online technical docs at https://cice-consortium.github.io/Icepack/ 
Please suggest code reviewers in the column at right. 
Other Relevant Details:
I'm not sure what I did to fix the ISPOL restart, unless it's because I moved the initialization call for hbrine to before the call to restartfile.

### CODE REVIEW

**Comment by eclare108213** [comment]
I'm having trouble believing that I fixed the restart problem, so I want to run the test again to check... but not tonight.  @chrisknewman could you try running the base_suite test suite on your machine and report the results to the github test results page, please?  I'll also try it from the IC machines.

**Comment by chrisknewman** [comment]
I can confirm that the restart problem appears to be fixed.  Test results on my mac with gfortran 6.2.0 can be found here: https://github.com/CICE-Consortium/Test-Results/wiki/12a569c27807c4f53f0644b6f9e44b5f0b4d8932.180129185833

@eclare108213 suggests that @njeffery take a look at the results to confirm that they make sense from a BGC standpoint.

**Comment by eclare108213** [comment]
All tests pass using the intel compiler:
https://github.com/CICE-Consortium/Test-Results/wiki/12a569c27807c4f53f0644b6f9e44b5f0b4d8932.180129200304

**Comment by chrisknewman** [comment]
@eclare108213 all tests pass on my mac with intel 16.0.0

#------- 
#repo = https://github.com/eclare108213/Icepack.git
#bran = codecleanup2
#hash = 12a569c27807c4f53f0644b6f9e44b5f0b4d8932
#hshu = Elizabeth Hunke <eclare@lanl.gov>
#hshd = Sun Jan 28 21:49:59 2018 -0700
#date = 2018-01-29
#time = 19:52:44
#mach = loft
#user = cnewman
#vers = Icepack 0.1.1
#------- 
#---
PASS loft_smoke_col_1x1_diag1_run1year build
PASS loft_smoke_col_1x1_diag1_run1year run
PASS loft_smoke_col_1x1_diag1_run1year generate icepackv6.0.0bs
#---
PASS loft_smoke_col_1x1_debug_run1year build
PASS loft_smoke_col_1x1_debug_run1year run
PASS loft_smoke_col_1x1_debug_run1year generate icepackv6.0.0bs
#---
PASS loft_smoke_col_1x1_bgcISPOL_debug build
PASS loft_smoke_col_1x1_bgcISPOL_debug run
PASS loft_smoke_col_1x1_bgcISPOL_debug generate icepackv6.0.0bs
#---
PASS loft_smoke_col_1x1_debug_run1year_thermo1 build
PASS loft_smoke_col_1x1_debug_run1year_thermo1 run
PASS loft_smoke_col_1x1_debug_run1year_thermo1 generate icepackv6.0.0bs
#---
PASS loft_smoke_col_1x1_debug_run1year_swccsm3 build
PASS loft_smoke_col_1x1_debug_run1year_swccsm3 run
PASS loft_smoke_col_1x1_debug_run1year_swccsm3 generate icepackv6.0.0bs
#---
PASS loft_smoke_col_1x1_alt01_debug_run1year build
PASS loft_smoke_col_1x1_alt01_debug_run1year run
PASS loft_smoke_col_1x1_alt01_debug_run1year generate icepackv6.0.0bs
#---
PASS loft_smoke_col_1x1_debug_dt30min_leap_run1year build
PASS loft_smoke_col_1x1_debug_dt30min_leap_run1year run
PASS loft_smoke_col_1x1_debug_dt30min_leap_run1year generate icepackv6.0.0bs
#---
PASS loft_smoke_col_1x1_debug_dyn_run1year build
PASS loft_smoke_col_1x1_debug_dyn_run1year run
PASS loft_smoke_col_1x1_debug_dyn_run1year generate icepackv6.0.0bs
#---
PASS loft_restart_col_1x1_debug build
PASS loft_restart_col_1x1_debug run-initial
PASS loft_restart_col_1x1_debug run-restart
PASS loft_restart_col_1x1_debug exact-restart
PASS loft_restart_col_1x1_debug generate icepackv6.0.0bs
#---
PASS loft_restart_col_1x1_diag1 build
PASS loft_restart_col_1x1_diag1 run-initial
PASS loft_restart_col_1x1_diag1 run-restart
PASS loft_restart_col_1x1_diag1 exact-restart
PASS loft_restart_col_1x1_diag1 generate icepackv6.0.0bs
#---
PASS loft_restart_col_1x1_pondcesm build
PASS loft_restart_col_1x1_pondcesm run-initial
PASS loft_restart_col_1x1_pondcesm run-restart
PASS loft_restart_col_1x1_pondcesm exact-restart
PASS loft_restart_col_1x1_pondcesm generate icepackv6.0.0bs
#---
PASS loft_restart_col_1x1_pondlvl build
PASS loft_restart_col_1x1_pondlvl run-initial
PASS loft_restart_col_1x1_pondlvl run-restart
PASS loft_restart_col_1x1_pondlvl exact-restart
PASS loft_restart_col_1x1_pondlvl generate icepackv6.0.0bs
#---
PASS loft_restart_col_1x1_pondtopo build
PASS loft_restart_col_1x1_pondtopo run-initial
PASS loft_restart_col_1x1_pondtopo run-restart
PASS loft_restart_col_1x1_pondtopo exact-restart
PASS loft_restart_col_1x1_pondtopo generate icepackv6.0.0bs
#---
PASS loft_restart_col_1x1_bgcISPOL build
PASS loft_restart_col_1x1_bgcISPOL run-initial
PASS loft_restart_col_1x1_bgcISPOL run-restart
PASS loft_restart_col_1x1_bgcISPOL exact-restart
PASS loft_restart_col_1x1_bgcISPOL generate icepackv6.0.0bs
#---
PASS loft_restart_col_1x1_thermo1 build
PASS loft_restart_col_1x1_thermo1 run-initial
PASS loft_restart_col_1x1_thermo1 run-restart
PASS loft_restart_col_1x1_thermo1 exact-restart
PASS loft_restart_col_1x1_thermo1 generate icepackv6.0.0bs
#---
PASS loft_restart_col_1x1_swccsm3 build
PASS loft_restart_col_1x1_swccsm3 run-initial
PASS loft_restart_col_1x1_swccsm3 run-restart
PASS loft_restart_col_1x1_swccsm3 exact-restart
PASS loft_restart_col_1x1_swccsm3 generate icepackv6.0.0bs
#---
PASS loft_restart_col_1x1_alt01 build
PASS loft_restart_col_1x1_alt01 run-initial
PASS loft_restart_col_1x1_alt01 run-restart
PASS loft_restart_col_1x1_alt01 exact-restart
PASS loft_restart_col_1x1_alt01 generate icepackv6.0.0bs
#---
PASS loft_restart_col_1x1_dyn build
PASS loft_restart_col_1x1_dyn run-initial
PASS loft_restart_col_1x1_dyn run-restart
PASS loft_restart_col_1x1_dyn exact-restart
PASS loft_restart_col_1x1_dyn generate icepackv6.0.0bs

74 of 74 tests PASSED
0 of 74 tests FAILED
0 of 74 tests PENDING

**Pull request merged**
